[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/bots",
    "crates/match",
    "crates/simulator",
    "crates/protocol",
    "crates/session",
    "crates/cli",
    "examples/tic_tac_toe",
    "examples/high_card",
    "examples/coup",
    "examples/rock_paper_scissors",
    "examples/minion_battle",
    "examples/risk",
    "examples/blackjack",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/crates-lurey-io/turnbase"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
